### ISSUE TITLE
Issue running code

### ISSUE THREAD

**Issue by mahdihey** [sony/nnabla-nas#45] opened 2022-08-31 00:29 UTC
I am trying to run nnabla-nas. I installed all the requirements and nnabla nnabla_ext_cuda110 nnabla_ext_cuda110_nccl2_mpi3_1_6 nnabla-converter. However, it gives the following error. The error is the same for all experiments provided.

> $ python main.py experiment=classification/pnas/cifar10_search[2022-08-31 00:16:26,863][nnabla][INFO] - Initializing CPU extension...
> [2022-08-31 00:16:27,912][nnabla][INFO] - Initializing CUDA extension...
> [2022-08-31 00:16:28,753][nnabla][INFO] - Initializing cuDNN extension...
> value error in query
> /home/gitlab-runner/builds/LRsSYq-B/0/nnabla/builders/all/nnabla/include/nbla/function_registry.hpp:70
> Failed `it != items_.end()`: Any of [cudnn:float, cuda:float, cpu:float] could not be found in []
> 
> No communicator found. Running with a single process. If you run this with MPI processes, all processes will perform totally same.
> [2022-08-31 00:16:31,195][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 00:16:31,195][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 00:16:31,195][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 00:16:31,195][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 00:16:34,866][nnabla][INFO] - DataSource with shuffle(True)
> [2022-08-31 00:16:34,867][nnabla][INFO] - Using DataIterator
> [2022-08-31 00:16:34,870][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 00:16:34,870][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 00:16:34,870][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 00:16:34,871][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 00:16:38,515][nnabla][INFO] - DataSource with shuffle(True)
> [2022-08-31 00:16:38,515][nnabla][INFO] - Using DataIterator
> [2022-08-31 00:16:38,517][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 00:16:38,517][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 00:16:38,518][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 00:16:38,518][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 00:16:40,615][nnabla][INFO] - DataSource with shuffle(False)
> [2022-08-31 00:16:40,615][nnabla][INFO] - Using DataIterator
> [2022-08-31 00:16:40,617][nnabla][INFO] - Saving experiment results to log/classification/pnas/cifar10/search/
> NNABLA_NAS_MIXEDOP_FAST_MODE is disabled
> warm-up epoch=0 lr=0.02500
> [  0/175]       error/train 0.922 (0.887)       loss/train 2.423 (2.470)
> [ 20/175]       error/train 0.828 (0.866)       loss/train 4.483 (5.346)
> Error executing job with overrides: ['experiment=classification/pnas/cifar10_search']
> An error occurred during Hydra's exception formatting:
> AssertionError()
> Traceback (most recent call last):
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 254, in run_and_report
>     assert mdl is not None
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 28, in <module>
>     app()
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 95, in decorated_main
>     config_name=config_name,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 396, in _run_hydra
>     overrides=overrides,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 453, in _run_app
>     lambda: hydra.run(
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 296, in run_and_report
>     raise ex
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
>     return func()
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 456, in <lambda>
>     overrides=overrides,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in run
>     _ = ret.return_value
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 260, in return_value
>     raise self._return_value
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 186, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "main.py", line 24, in app
>     main(cfg)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/utils/cli/cli.py", line 92, in main
>     args=conf.hparams
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/search.py", line 28, in run
>     self._start_warmup()
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/search.py", line 57, in _start_warmup
>     self.train_on_batch(key='warmup')
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/pnas.py", line 36, in train_on_batch
>     self.update_graph(key)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/runner.py", line 129, in update_graph
>     outputs = model(*inputs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/network.py", line 79, in call
>     out_c, out_p = cell(out_p, out_c), out_c
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/modules.py", line 348, in call
>     s = sum(self._blocks[offset + j](h) for j, h in enumerate(out))
>   File "_variable.pyx", line 1110, in nnabla._variable.Variable.__add__
>   File "_arithmetic_ops.pyx", line 60, in nnabla._arithmetic_ops.add
>   File "<add2>", line 3, in add2
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/nnabla/function_bases.py", line 2360, in add2
>     return F.Add2(ctx, inplace)(x0, x1, n_outputs=n_outputs, auto_forward=get_auto_forward(), outputs=outputs)
>   File "function.pyx", line 328, in nnabla.function.Function.__call__
>   File "function.pyx", line 306, in nnabla.function.Function._cg_call
> RuntimeError: value error in setup_impl
> /home/gitlab-runner/builds/LRsSYq-B/0/nnabla/builders/all/nnabla/include/nbla/function/utils/base_transform_binary.hpp:74
> Failed `std::min(s0[i], s1[i]) == 1`: Broadcast dimension must be one. shape[2]: 28.

**Comment by mahdihey** [comment] 2022-08-31 00:36
$  pip list|grep nnabla
nnabla                             1.29.0
nnabla-converter                   1.29.0
nnabla-ext-cuda110                 1.29.0
nnabla-ext-cuda110-nccl2-mpi3-1-6  1.29.0

**Comment by TomonobuTsujikawa** [comment] 2022-08-31 01:03
You should install only one of `nnabla-ext-cuda110` or `nnabla-ext-cuda110-nccl2-mpi3-1-6`.
I believe that `nnabla-ext-cuda110` can support single and multi GPU now. so, please try the following.

```bash
pip uninstall nnabla nnabla-ext-cuda110 nnabla-ext-cuda110-nccl2-mpi3-1-6
pip install nnabla-ext-cuda110
```

**Comment by TomonobuTsujikawa** [comment] 2022-08-31 02:55
Sorry, I though that you don't need to uninstall nnabla-converter, but I was wrong.
Please uninstall nnabla-converter, too.
Also, please change install wheel from `nnabla-ext-cuda110` to `nnabla-ext-cuda110-nccl2-mpi3-1-6` if you have a plan to use multi GPU.

```bash
pip uninstall nnabla nnabla-ext-cuda110 nnabla-converter
pip install nnabla-ext-cuda110-nccl2-mpi3-1-6 nnabla-converter
```

**Comment by mahdihey** [comment] 2022-08-31 03:20
Thanks, I did as you said. Here is the new output.

> $ python main.py experiment=classification/pnas/cifar10_search
> [2022-08-31 03:17:20,969][nnabla][INFO] - Initializing CPU extension...
> [2022-08-31 03:17:22,041][nnabla][INFO] - Initializing CUDA extension...
> [2022-08-31 03:17:22,903][nnabla][INFO] - Initializing cuDNN extension...
> [2022-08-31 03:17:25,701][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 03:17:25,701][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 03:17:25,702][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 03:17:25,702][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 03:17:29,449][nnabla][INFO] - DataSource with shuffle(True)
> [2022-08-31 03:17:29,450][nnabla][INFO] - Using DataIterator
> [2022-08-31 03:17:29,453][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 03:17:29,453][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 03:17:29,453][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 03:17:29,454][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 03:17:33,189][nnabla][INFO] - DataSource with shuffle(True)
> [2022-08-31 03:17:33,190][nnabla][INFO] - Using DataIterator
> [2022-08-31 03:17:33,192][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 03:17:33,193][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 03:17:33,193][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 03:17:33,193][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 03:17:35,284][nnabla][INFO] - DataSource with shuffle(False)
> [2022-08-31 03:17:35,284][nnabla][INFO] - Using DataIterator
> [2022-08-31 03:17:35,288][nnabla][INFO] - Saving experiment results to log/classification/pnas/cifar10/search/
> NNABLA_NAS_MIXEDOP_FAST_MODE is disabled
> warm-up epoch=0 lr=0.02500
> [  0/175]       error/train 0.891 (0.898)       loss/train 2.548 (2.547)
> [ 20/175]       error/train 0.844 (0.866)       loss/train 6.023 (5.491)
> Error executing job with overrides: ['experiment=classification/pnas/cifar10_search']
> An error occurred during Hydra's exception formatting:
> AssertionError()
> Traceback (most recent call last):
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 254, in run_and_report
>     assert mdl is not None
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 28, in <module>
>     app()
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 95, in decorated_main
>     config_name=config_name,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 396, in _run_hydra
>     overrides=overrides,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 453, in _run_app
>     lambda: hydra.run(
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 296, in run_and_report
>     raise ex
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
>     return func()
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 456, in <lambda>
>     overrides=overrides,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in run
>     _ = ret.return_value
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 260, in return_value
>     raise self._return_value
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 186, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "main.py", line 24, in app
>     main(cfg)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/utils/cli/cli.py", line 92, in main
>     args=conf.hparams
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/search.py", line 28, in run
>     self._start_warmup()
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/search.py", line 57, in _start_warmup
>     self.train_on_batch(key='warmup')
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/pnas.py", line 36, in train_on_batch
>     self.update_graph(key)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/runner.py", line 129, in update_graph
>     outputs = model(*inputs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/network.py", line 79, in call
>     out_c, out_p = cell(out_p, out_c), out_c
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/modules.py", line 348, in call
>     s = sum(self._blocks[offset + j](h) for j, h in enumerate(out))
>   File "_variable.pyx", line 1110, in nnabla._variable.Variable.__add__
>   File "_arithmetic_ops.pyx", line 60, in nnabla._arithmetic_ops.add
>   File "<add2>", line 3, in add2
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/nnabla/function_bases.py", line 2360, in add2
>     return F.Add2(ctx, inplace)(x0, x1, n_outputs=n_outputs, auto_forward=get_auto_forward(), outputs=outputs)
>   File "function.pyx", line 328, in nnabla.function.Function.__call__
>   File "function.pyx", line 306, in nnabla.function.Function._cg_call
> RuntimeError: value error in setup_impl
> /home/gitlab-runner/builds/LRsSYq-B/0/nnabla/builders/all/nnabla/include/nbla/function/utils/base_transform_binary.hpp:74
> Failed `std::min(s0[i], s1[i]) == 1`: Broadcast dimension must be one. shape[2]: 28.

**Comment by TomonobuTsujikawa** [comment] 2022-08-31 04:07
I think your environment setup correctly now.

Regarding to pnas error, we also face this error.
But, the root cause is not yet identified.
We'll investigate this issue, and will let you know if we find a root cause or workaround.

**Comment by mahdihey** [comment] 2022-08-31 04:12
Thanks for your help. I think the issue may be for other too. Here is the log for DARTS:

> $ python main.py experiment=classification/darts/cifar10_search
> [2022-08-31 04:10:14,432][nnabla][INFO] - Initializing CPU extension...
> [2022-08-31 04:10:15,497][nnabla][INFO] - Initializing CUDA extension...
> [2022-08-31 04:10:16,354][nnabla][INFO] - Initializing cuDNN extension...
> [2022-08-31 04:10:18,019][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 04:10:18,020][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 04:10:18,020][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 04:10:18,020][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 04:10:21,684][nnabla][INFO] - DataSource with shuffle(True)
> [2022-08-31 04:10:21,685][nnabla][INFO] - Using DataIterator
> [2022-08-31 04:10:21,687][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 04:10:21,687][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 04:10:21,688][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 04:10:21,688][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 04:10:25,337][nnabla][INFO] - DataSource with shuffle(True)
> [2022-08-31 04:10:25,337][nnabla][INFO] - Using DataIterator
> [2022-08-31 04:10:25,340][nnabla][INFO] - Getting labeled data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz.
> [2022-08-31 04:10:25,340][nnabla][INFO] - > /home/ec2-user/nnabla_data/cifar-10-python.tar.gz already exists.
> [2022-08-31 04:10:25,340][nnabla][INFO] - > If you have any issue when using this file,
> [2022-08-31 04:10:25,340][nnabla][INFO] - > manually remove the file and try download again.
> [2022-08-31 04:10:27,448][nnabla][INFO] - DataSource with shuffle(False)
> [2022-08-31 04:10:27,449][nnabla][INFO] - Using DataIterator
> [2022-08-31 04:10:27,452][nnabla][INFO] - Saving experiment results to log/classification/darts/cifar10/search/
> NNABLA_NAS_MIXEDOP_FAST_MODE is disabled
> Error executing job with overrides: ['experiment=classification/darts/cifar10_search']
> An error occurred during Hydra's exception formatting:
> AssertionError()
> Traceback (most recent call last):
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 254, in run_and_report
>     assert mdl is not None
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 28, in <module>
>     app()
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 95, in decorated_main
>     config_name=config_name,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 396, in _run_hydra
>     overrides=overrides,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 453, in _run_app
>     lambda: hydra.run(
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 296, in run_and_report
>     raise ex
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
>     return func()
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 456, in <lambda>
>     overrides=overrides,
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in run
>     _ = ret.return_value
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 260, in return_value
>     raise self._return_value
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 186, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "main.py", line 24, in app
>     main(cfg)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/utils/cli/cli.py", line 92, in main
>     args=conf.hparams
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/search.py", line 25, in run
>     self.callback_on_start()
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/searcher/darts.py", line 24, in callback_on_start
>     self.update_graph('train')
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/runner/runner.py", line 129, in update_graph
>     outputs = model(*inputs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/network.py", line 79, in call
>     out_c, out_p = cell(out_p, out_c), out_c
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/modules.py", line 348, in call
>     s = sum(self._blocks[offset + j](h) for j, h in enumerate(out))
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/modules.py", line 348, in <genexpr>
>     s = sum(self._blocks[offset + j](h) for j, h in enumerate(out))
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/contrib/classification/darts/modules.py", line 262, in call
>     return self._mixed(input)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/module.py", line 630, in __call__
>     return self.call(*args, **kwargs)
>   File "/home/ec2-user/SageMaker/nnabla-nas/nnabla_nas/module/mixedop.py", line 142, in call
>     h = F.stack(*[op(input) for op in self._ops], axis=0)
>   File "<stack>", line 3, in stack
>   File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/nnabla/function_bases.py", line 3846, in stack
>     return F.Stack(ctx, axis)(*x, n_outputs=n_outputs, auto_forward=get_auto_forward(), outputs=outputs)
>   File "function.pyx", line 328, in nnabla.function.Function.__call__
>   File "function.pyx", line 306, in nnabla.function.Function._cg_call
> RuntimeError: value error in setup_impl
> /home/gitlab-runner/builds/LRsSYq-B/0/nnabla/builders/all/nnabla/src/nbla/function/./generic/stack.cpp:44
> Failed `inputs[i]->shape() == in_shape`: All inputs must be the same size. inputs[5] shape: (16, 16, 30, 30) != inputs[0] shape: (16, 16, 32, 32).

**Comment by TomonobuTsujikawa** [comment] 2022-09-01 09:21
I think this issue is fixed by https://github.com/sony/nnabla-nas/pull/46.
Please check it again!

**Comment by TomonobuTsujikawa** [comment] 2022-09-28 00:33
This issue is already fixed, so please let me close.

**Closed by TomonobuTsujikawa** 2022-09-28 00:33 UTC
